version: "3.7"
services:
        apache:
                container_name: apache
                build: ./docker/apache
                ports:
                        - 8080:80
                depends_on:
                        - php
                        - mysql
                volumes:
                        - .:/var/www/app

        mysql:
                container_name: mysql
                image: mysql
                restart: always
                volumes:
                        - ./docker/data/db:/var/lib/mysql
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: app
                        MYSQL_USER: khan
                        MYSQL_PASSWORD: khan
        
        php:
                container_name: php
                build: ./docker/php
                working_dir: /var/www/app
                volumes:
                        - .:/var/www/app
